name: 'Shopify Theme Download'
description: 'Pulls changes from Shopify Theme Kit themes'
branding:
  icon: 'download'  
  color: 'green'
runs:
  using: "composite"
  steps: 

    # Configure git.
    - shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    # Run action.
    - shell: bash
      run: ${{ github.action_path }}/action.sh